name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Instalar dependências
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-lucro-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

env:
  ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node20
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
